radar/humanize

humanize.gemspec

As @radar is maintaining this gem, it makes sense to me that the home page URL on RubyGems.org should point to the right page on Github. The old URL went directly to a 404 page. This one doesn't!

Update homepage URL in humanize.gemspec

---

.gitignore
Gemfile.lock
README.markdown
bin/run_mutant
humanize.gemspec
lib/humanize.rb
lib/words.rb
spec/configuration_spec.rb
spec/humanize_spec.rb
spec/spec_helper.rb
spec/tests.rb

After using the gem in my project I realized there was quirk with a specific french case.
`one thousand` is not translated to `un mille` in french, but rather just `mille`. So I added a condition for that particular case in that particular locale. After thinking a bit about it it might be the only specific case.
In the process I realized I did not include specs for the `decimals_as` options. So I added them.
Using mutation testing with `mutant` helped me realize I did not include the tests, so I added it to the project with a little script to simplify running it.
If you don't want to include it, tell me I'll remove the commit from the pull request.

Adds missing specs, fixes french specific case, installs testing tools

---

lib/humanize.rb
spec/humanize_spec.rb

Hi, @radar!
There is a bug in the number `1000` in the Indonesian locale I wrote.
`1000` in Indonesian language is kind of interesting.
No other numbers possess the same behaviour.
The quirks are:
* When it is the lone thousand in its thousands range, `satu` (one) and `ribu` (thousand) merge to become `seribu` (one thousand).
* When it is not the lone thousand in its thousands range, `satu` and `ribu` do not merge. 
Other numbers are either always merge: `satu` and `puluh`(ten(s)) => `sepuluh` (ten), and `satu` and `ratus` (hundred(s)) => `seratus` (one hundred); or never merge: `satu` and `juta` (million) => `satu juta` (one million), `satu` and `miliar` (billion) => `satu miliar` (one billion), and so on.

Patch 1000 issue in Indonesian language

---

lib/humanize.rb

Hi, @radar.
I think I catch another thing that can be improved a little.
The `gsub` to remove extra chars (spaces in this case) can be replaced with its cousin `squeeze` that is made specifically for this.
You can test them with this:
```ruby
o = "words with   extra  spaces in the middle"
o.gsub(/ +/, ' ')
o.squeeze(' ')
Benchmark.ips do |x|
x.config(:time => 10, :warmup => 3)
x.report("gsub") do
o.gsub(/ +/, ' ')
end
x.report("squeeze") do
o.squeeze(' ')
end
x.compare!
end
```
Result:

Improve performance of extra spaces removal

---

lib/humanize.rb
spec/tests.rb

Hi, @radar. This should fix the issue #29 that I found.
`to_i` is not needed here since `self` is already of type `Numeric` (module is included to `Numeric`).
I also commit `Gemfile.lock` to fix the CI error.

Fix issue #29 where number -0.XXX is read without the `negative`.

---

lib/humanize.rb
spec/tests.rb

Hi, @radar.
I think this could fix issue #31 that is caused by ruby printing floats in scientific notation after 5 decimal places.

Fix issue #31 where float conversions break after 5 decimal places

---

README.markdown

@radar, I want to fix these on the readme:
- Call `humanize` on 9s.
- Fix install guide. It should be:  install from terminal **or** add to Gemfile and then `require` it.
- Use triple backticks (```) instead of indentations to render them nicely on github.
- Add `:id` to the list of locale in the configuration example.
- Remove trailing comma after `:fr`.
What do you think?

Fix readme

---

lib/humanize.rb
lib/humanize/words.rb
spec/humanize_spec.rb

@radar, instead of raising error when called on conceptual numbers, I'm thinking of supporting them.
So, instead of these:
```ruby
(1/0.0).humanize
#=> FloatDomainError: Infinity
(-1/0.0).humanize
#=> FloatDomainError: Infinity
(0/0.0).humanize
#=> FloatDomainError: NaN
```
We can do these:
```ruby
(1/0.0).humanize
#=> "infinity"
(-1/0.0).humanize
#=> "negative infinity"
(0/0.0).humanize
#=> "undefined"
```
But, first, I need @axelerator and @mertbulan to verify the words for 'undefined' and 'infinity', that I got from google translate, in German and Turkish. For French, can anyone check it?

Support infinity and undefined

---

humanize.gemspec
lib/humanize.rb

Prefer to use keyword arguments to options hash for these reasons:
- Fewer characters or lines of code to type.
- We can immediately discover the names of the arguments without having to read the body of the method.
- Less chance of typos if in the future we want to add new arguments since we don’t have to write the boilerplate code to extract hash options.
Source: [Ruby 2 Keyword Arguments](https://robots.thoughtbot.com/ruby-2-keyword-arguments#keyword-arguments-vs-options-hash)

Use keyword arguments instead of options hash

---

README.markdown

`1001.humanize` should be "one thousand and one".

Fix example on README [skip ci]

---

lib/humanize.rb
spec/humanize_spec.rb

Now:
```ruby
BigDecimal.new("10").humanize
#=> "ten"
```
Before, it was `NoMethodError`.

Support BigDecimal

---

lib/humanize.rb

Fixes #56.
It seems that it's not used or documented anywhere. Also, it shouldn't work with any kind of input.

Remove decimals_as_number

---

lib/humanize/locales.rb

Most people usually only use one or maybe some locales, not all of them. And because it seems that `autoload`'s live has been [prolonged](https://bugs.ruby-lang.org/issues/5653#note-46), I'm thinking of `autoload`ing them to prevent loading unused locales.

Autoload locales

---

.travis.yml

- No reason to test on ruby version **2.3.x**, as it's not maintained anymore
- Remove `sudo: false` because [this](https://changelog.travis-ci.com/linux-builds-run-on-vms-by-default-77106).

Update ruby versions and remove `sudo: false`

---

.rubocop.yml
humanize.gemspec

I'm working on to contribute `:vi` locale and I realize I can't run rubocop:
```bash
$ bundle exec rubocop
.rubocop.yml: Metrics/LineLength has the wrong namespace - should be Layout
Error: RuboCop found unsupported Ruby version 2.3 in `TargetRubyVersion` parameter (in .rubocop.yml). 2.3-compatible analysis was dropped after version 0.81.
Supported versions: 2.4, 2.5, 2.6, 2.7, 3.0
```
Because [Rubocop drop support for Ruby 2.3](https://github.com/rubocop-hq/rubocop/pull/7869/files) and [support of Ruby 2.3 has ended](https://www.ruby-lang.org/en/news/2019/03/31/support-of-ruby-2-3-has-ended/)
So I think we should update ruby version to 2.4.

Drop support for ruby 2.3

---

lib/humanize/locales/fr.rb
spec/locales/fr_spec.rb

In french when we have multiple million/billion and other big numbers there is an s at the end 🥐

fix: plural for lots in french version

---

humanize.gemspec

Does exactly what it says on the tin! RubyGems.org will display the project's license information on the gem's page.
Reference: https://guides.rubygems.org/specification-reference/#metadata

Add license to gem metadata

---

humanize.gemspec

The `gemspec` file supports [a bunch of metadata](https://guides.rubygems.org/specification-reference/#metadata). Among that are a couple of `*_uri` methods that RubyGems.org will helpfully show in the sidebar of a page when viewing a gem ([example](https://rubygems.org/gems/link-header-parser)).
This PR adds two of those pieces of metadata:
- `bug_tracker_uri` pointing to the project's GitHub Issues page, and
- `source_code_uri` which dynamically links to the published version's source tree on GitHub.
The latter is most helpful when browsing versions of the gem on RubyGems.org. Having a direct link to that version's tag on GitHub is super handy.
At a minimum, I'd like to also add a `changelog_uri` to the gem's metadata. The project doesn't currently have a `CHANGELOG.md` (or similar) and …

Add issues and source code metadata to gemspec

---

humanize.gemspec

Hello! Thanks for considering this change.
This PR replaces the `s.files` value in `humanize.gemspec`, removing the reliance on a system installation of Git. The replacement globs files from `lib` and appends a few other useful files into the built gem.
As a bonus, this should trim back a bit on the published gem size (about 30k in a quick local test).

Pure Ruby `s.files` using `Dir[]`

---

.rubocop_todo.yml
Gemfile
humanize.gemspec

This PR moves the project's development dependencies from its gemspec to `Gemfile` following RuboCop's `Gemspec/DevelopmentDependencies` (rubocop/rubocop#11469) recommendation. There's some debate on that PR over the change, but in the spirit of leaning in to community defaults, this change moves those dependencies.
I'll admit to not knowing this project's maintainers well enough to know whether or not y'all prefer this particular recommendation. If it's undesirable, we can close this one out and/or move the rule's configuration from the todo file to the main `.rubocop.yml` file.

Move development dependencies to `Gemfile`
